server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yiwenluohx/springcloud-config.git
          search-paths: #搜索目录
            - springcloud-config
          force-pull: true
          username: xxxx
          password: xxxxx
      label: main #读取的分支

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #集群版
      #      defaultZone: http://localhost:7001/eureka  #单机处理