server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        enabled: true #解决restTemplate负载链接拒绝
        prefer-ip-address: true
#        ip-address: 127.0.0.1